# Generated by Django 3.0.3 on 2020-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200927_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
